### API error 404
GET http://localhost:3000/rdfhf





## USER

### test login
GET http://localhost:3000/login


### update user password
PATCH http://localhost:3000/profile/parent/2
Content-Type: application/json

{
    "password": "Chicagoland"
}


### update user info
PATCH http://localhost:3000/profile/parent/1/info
Content-Type: application/json

{
    "address": "50 rue de Paris",
    "postcode": "12345",
    "city": "Marigny",
    "phone_number": "0611203948"
}
