## TEST HTTP

### API error 404
GET http://localhost:3000/rdfhf


### DISPLAYING ALL OF THE USERS - for admin only
GET http://localhost:3000/profile/admin/allusers

### DISPLAYING ALL PARENTS - for admin
GET http://localhost:3000/profile/admin/parents

### DISPLAYING ALL STAFF MEMBERS - for admin
GET http://localhost:3000/profile/admin/allstaff

### DISPLAYING ALL CHILDREN - for admin
GET http://localhost:3000/profile/admin/children

### DISPLAYING ALL RECAPS - for staff
GET http://localhost:3000/profile/staff/allrecaps

### DISPLAYING ALL COMMENTS - for staff
GET http://localhost:3000/profile/staff/comments

### DISPLAYING COMMENTS BY PARENT ID - for staff
GET http://localhost:3000/profile/staff/comments/parent/3


### DISPLAYING COMMENTS BY PARENT ID - for parents
GET http://localhost:3000/profile/parent/3/comments


### DISPLAYING PARENT PROFILE - parent by id
GET http://localhost:3000/profile/parent/8

### DISPLAYING CHILD ACCORDING TO PARENT PROFILE
GET http://localhost:3000/profile/parent/1/child/2

### DISPLAYING STAFF PROFILE - staff by id
GET http://localhost:3000/profile/staff/5

### DISPLAYING RECAP - by id
GET http://localhost:3000/profile/staff/recap/1

### DISPLAYING RECAPS - by child id
GET http://localhost:3000/profile/staff/child/1/recaps

### DISPLAYING COMMENT - by id
GET http://localhost:3000/profile/staff/comments/3


### DISPLAYING COMMENTS - by child id
GET http://localhost:3000/profile/staff/comments/child/4


### MODIFY CHILD PROFILE - by parent
PATCH http://localhost:3000/profile/parent/2/child/3
Content-Type: application/json

{
    "first_name": "olivier",
    "birthplace": "nantes"
}

### MODIFY CHILD PROFILE - by admin
PATCH http://localhost:3000/profile/admin/parent/2/managechildren/3
Content-Type: application/json

{
    "first_name": "Charles",
    "birthplace": "Orvault"
}

### DELETE CHILD PROFILE - by adminController
DELETE http://localhost:3000/profile/admin/parent/2/managechildren/3


## USER

### try login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "mauricettequatre@laposte.net",
    "password": "testouille"
}

### try login with other user - hashed password to try with bcrypt compareSync 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "gaspardfait@hotmail.fr",
    "password": "g4sp4rd!"
}


### try login - wrong password
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "nicoassezadmin@gmail.com",
    "password": "fgrfdg"
}


### update parent password
PATCH http://localhost:3000/profile/parent/2/password
Content-Type: application/json

{
    "password": "g4sp4rd!"
}



### update staff password
PATCH http://localhost:3000/profile/staff/5/password
Content-Type: application/json

{
    "password": "testouille"
}


### update user info

PATCH http://localhost:3000/profile/parent/8/
Content-Type: application/json

{
    "phone_number": "0123456789"
}


# ADMIN

### adding an user
POST http://localhost:3000/profile/admin/manageprofile
Content-Type: application/json

{
    "first_name": "Mickael",
    "last_name": "Menet",
    "address": "50 rue de Paris",
    "postcode": "12345",
    "city": "Marigny",
    "email": "mickaeldu59@gmail.com",
    "password": "monsuperpassword",
    "phone_number": "0611203948",
    "role_id": 1
}

# a tester?
# ### logout user
# GET http://localhost:3000/logout


### deleting an user
DELETE http://localhost:3000/profile/admin/manageprofile/8

### adding a child
POST http://localhost:3000/profile/admin/parent/3/managechildren
Content-Type: application/json

{
    "first_name": "Mickael",
    "last_name": "Menet",
    "birthdate": "18/04/1995",
    "birthplace": "Metz",
    "sex": "F",
    "allergies": "amandes"
}

# RECAP

### add recap
POST http://localhost:3000/profile/staff/child/recap/
Content-Type: application/json

{
    "date": "10/08/2019",
    "extra_info": "a été sage toute la journée",
    "mood": "fatigué",
    "child_id": 1
}

### modify one field 
PATCH http://localhost:3000/profile/staff/child/recap/3/
Content-Type: application/json

{
    "date": "18/05/2025"
}

### delete
DELETE http://localhost:3000/profile/staff/child/recap/13




# COMMENTS

### add comment
POST http://localhost:3000/profile/parent/comments/
Content-Type: application/json

{
    "message": "mal dormi !!!",
    "child_id": 2
}

### modify comment
PATCH http://localhost:3000/profile/parent/comments/5
Content-Type: application/json

{
    "message": "en fait ça va mieux maintenant",
    "child_id": 2
}

### delete comment
DELETE http://localhost:3000/profile/parent/comments/5