### API error 404
GET http://localhost:3000/rdfhf



## USER
### update user password
PUT http://localhost:3000/profile/parent/1
Content-Type: application/json

{
    "email": "jeannebonnette@gmail.com",
    "password": "Chicagoland",
    "passwordConfirm": "Chicagoland"
}


